const CONSTS = {
  FONT_SIZE: 18,
  CONTAINER_BORDER_RADIUS: 10,
  PADDING_HORIZONTAL: 20,
  PADDING_VERTICAL: 15,
  LINE_HEIGHT: 32,
  IMAGE_HEIGHT: 200,
  TITLE_MAX_LINES: 1,
  SUBTITLE_MAX_LINES: 3
}

export default CONSTS
