const CONSTS = {
  TITLE_FONT_SIZE: 25,
  SUBTITLE_FONT_SIZE: 18,
  PADDING_HORIZONTAL: 20,
  PADDING_VERTICAL: 15,
  LINE_HEIGHT: 40,
  IMAGE_HEIGHT:300,
  AVATAR_SIZE: 80,
  TOTAL_LINE_HEIGHT: 30,
}

export default CONSTS
